In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# 2/2, Home, Alls-Chatty, Brawls-BlueWhite
# 3/3, Away, Brawls-Cornfed, Brawls-BleedingHeartland, Brawls-RoyalCity
# 3/9, Home, Alls-BlackRose, Brawls-BlackRose
# 3/23, Away, Alls-TragicCity
# 4/6, Away, Alls-PennJersey
# 4/7, Away, Alls-Downriver, Alls-ForestCity
# 5/18, Away, Alls-ArchRival, Brawls-ArchRival
# 6/15, Away, Alls-BERG
# 6/16, Away, Alls-RedStick
# 7/13, Home, Alls-Fayetteville, Brawls-WindyCity
# 8/17, Home, Alls-ArchRival , Brawls-ArchRival
# 8/31, Away, Alls-Chatty, Brawls-Chatty

In [ ]:
# 2/2, Home, Alls-Chatty, 
_0202Allspath = "0202Alls.csv"
_0202Alls_df = pd.read_csv(_0202Allspath, encoding="ISO-8859-1")

_0202Alls_df['Game Date'] = '020219'
_0202Alls_df['Team'] = 'Alls'
_0202Alls_df['Home/Away'] = 'Home'
_0202Alls_df['Opponent'] = 'Chatty'


# 3/3, Away, Brawls1-Cornfed, Brawls2-BleedingHeartland, Brawls3-RoyalCity
_03031Brawlspath = "0303-1-Brawls.csv"
_03031Brawls_df = pd.read_csv(_03031Brawlspath, encoding="ISO-8859-1")

_03031Brawls_df['Game Date'] = '030319'
_03031Brawls_df['Team'] = 'Brawls'
_03031Brawls_df['Home/Away'] = 'Away'
_03031Brawls_df['Opponent'] = 'Cornfed'


_03032Brawlspath = "0303-2-Brawls.csv"
_03032Brawls_df = pd.read_csv(_03032Brawlspath, encoding="ISO-8859-1")

_03032Brawls_df['Game Date'] = '030319'
_03032Brawls_df['Team'] = 'Brawls'
_03032Brawls_df['Home/Away'] = 'Away'
_03032Brawls_df['Opponent'] = 'BleedingHeartland'


_03033Brawlspath = "0303-3-Brawls.csv"
_03033Brawls_df = pd.read_csv(_03033Brawlspath, encoding="ISO-8859-1")

_03033Brawls_df['Game Date'] = '030319'
_03033Brawls_df['Team'] = 'Brawls'
_03033Brawls_df['Home/Away'] = 'Away'
_03033Brawls_df['Opponent'] = 'RoyalCity'


# 3/9, Home, Alls-BlackRose, Brawls-BlackRose
_0309Allspath = "0309Alls.csv"
_0309Alls_df = pd.read_csv(_0309Allspath, encoding="ISO-8859-1")

_0309Alls_df['Game Date'] = '030919'
_0309Alls_df['Team'] = 'Alls'
_0309Alls_df['Home/Away'] = 'Home'
_0309Alls_df['Opponent'] = 'BlackRose'


_0309Brawlspath = "0309Brawls.csv"
_0309Brawls_df = pd.read_csv(_0309Brawlspath, encoding="ISO-8859-1")

_0309Brawls_df['Game Date'] = '030919'
_0309Brawls_df['Team'] = 'Brawls'
_0309Brawls_df['Home/Away'] = 'Home'
_0309Brawls_df['Opponent'] = 'BlackRose'


# 3/23, Away, Alls-TragicCity
_0323Allspath = "0323Alls.csv"
_0323Alls_df = pd.read_csv(_0323Allspath, encoding="ISO-8859-1")

_0323Alls_df['Game Date'] = '032319'
_0323Alls_df['Team'] = 'Alls'
_0323Alls_df['Home/Away'] = 'Away'
_0323Alls_df['Opponent'] = 'TragicCity'


# 4/6, Away, Alls-PennJersey
_0406Allspath = "0406Alls.csv"
_0406Alls_df = pd.read_csv(_0406Allspath, encoding="ISO-8859-1")

_0406Alls_df['Game Date'] = '040619'
_0406Alls_df['Team'] = 'Alls'
_0406Alls_df['Home/Away'] = 'Away'
_0406Alls_df['Opponent'] = 'PennJersey'


# 4/7, Away, Alls-Downriver, Alls-ForestCity
_04071Allspath = "0407-1-Alls.csv"
_04071Alls_df = pd.read_csv(_04071Allspath, encoding="ISO-8859-1")

_04071Alls_df['Game Date'] = '040719'
_04071Alls_df['Team'] = 'Alls'
_04071Alls_df['Home/Away'] = 'Away'
_04071Alls_df['Opponent'] = 'DownRiver'

_04072Allspath = "0407-2-Alls.csv"
_04072Alls_df = pd.read_csv(_04072Allspath, encoding="ISO-8859-1")

_04072Alls_df['Game Date'] = '040719'
_04072Alls_df['Team'] = 'Alls'
_04072Alls_df['Home/Away'] = 'Away'
_04072Alls_df['Opponent'] = 'ForestCity'


# 5/18, Away, Alls-ArchRival, Brawls-ArchRival
#Data provided to us in pdf format only - is not part of this dataset


# 6/15, Away, Alls-BERG
_0615Allspath = "0615Alls.csv"
_0615Alls_df = pd.read_csv(_0615Allspath, encoding="ISO-8859-1")

_0615Alls_df['Game Date'] = '061519'
_0615Alls_df['Team'] = 'Alls'
_0615Alls_df['Home/Away'] = 'Away'
_0615Alls_df['Opponent'] = 'BERG'


# 6/16, Away, Alls-RedStick
_0616Allspath = "0616Alls.csv"
_0616Alls_df = pd.read_csv(_0616Allspath, encoding="ISO-8859-1")

_0616Alls_df['Game Date'] = '061619'
_0616Alls_df['Team'] = 'Alls'
_0616Alls_df['Home/Away'] = 'Away'
_0616Alls_df['Opponent'] = 'RedStick'



# 7/13, Home, Alls-Fayetteville, Brawls-WindyCity
_0713Allspath = "0713Alls.csv"
_0713Alls_df = pd.read_csv(_0713Allspath, encoding="ISO-8859-1")

_0713Alls_df['Game Date'] = '071319'
_0713Alls_df['Team'] = 'Alls'
_0713Alls_df['Home/Away'] = 'Home'
_0713Alls_df['Opponent'] = 'Fayetteville'


_0713Brawlspath = "0713Brawls.csv"
_0713Brawls_df = pd.read_csv(_0713Brawlspath, encoding="ISO-8859-1")

_0713Brawls_df['Game Date'] = '071319'
_0713Brawls_df['Team'] = 'Brawls'
_0713Brawls_df['Home/Away'] = 'Home'
_0713Brawls_df['Opponent'] = 'WindyCity'



# 8/17, Home, Alls-ArchRival , Brawls-ArchRival
# 8/31, Away, Alls-Chatty, Brawls-Chatty

In [ ]:
# Way oversimplifying everything, but I can throw them all together and then add everything up
# This would only be useful for the data in this set that can be summarized (like the number of times as jammer, total points, etc. )

home_away_counts = pd.concat([_0202Alls_df,  _03031Brawls_df, _03032Brawls_df, _03033Brawls_df, _0309Alls_df, _0309Brawls_df, _0323Alls_df, _0406Alls_df, _04071Alls_df, _04072Alls_df, _0615Alls_df, _0616Alls_df, _0713Alls_df, _0713Brawls_df]).groupby(['#']).sum().reset_index()
home_away_counts.head()

In [ ]:
home_away = home_away_counts[['#', 'JAMMER', 'PIVOT', 'BLOCKER', 'POINTS', 'LOST', 'LEAD', 'CALLED', 'NO INITIAL TRIP', 'STAR PASSES RECEIVED', 'PTS  FOR', 'PTS AGAINST', 'SKATERS PENALTY COUNT']]

In [ ]:
home_away
#home_away.to_csv("2019_Home_Away_Games_Alls-and-Brawls.csv")

In [78]:
all_df = pd.concat([_0202Alls_df,  _03031Brawls_df, _03032Brawls_df, _03033Brawls_df, _0309Alls_df, _0309Brawls_df, _0323Alls_df, _0406Alls_df, _04071Alls_df, _04072Alls_df, _0615Alls_df, _0616Alls_df, _0713Alls_df, _0713Brawls_df])
all_df.head()

,#,Skater,JAMMER,PIVOT,BLOCKER,TOTAL,% JAMS SKATED,POINTS,PPJ,LOST,...,VTAR JAMMER AVG +/-,VTAR PIVOT AVG +/-,VTAR BLOCKER AVG +/-,VTAR PACK\nAVG +/-,TOTAL VTAR AVG +/-,SKATERS PENALTY COUNT,Game Date,Team,Home/Away,Opponent
0,11,Polly Pushy Pants,0,0,10,10,23%,NaN,NaN,NaN,...,NaN,NaN,-0.52,-0.50,-0.52,6.0,020219,Alls,Home,Chatty
1,13,Surely Mental,3,0,3,6,14%,0.0,0.00,0.0,...,-4.66,NaN,0.92,0.94,-2.59,0.0,020219,Alls,Home,Chatty
2,23,Sintilly,0,14,7,21,49%,NaN,NaN,NaN,...,NaN,2.7,0.16,1.65,1.63,5.0,020219,Alls,Home,Chatty
3,124,Ka-Blamazon,0,0,16,16,37%,NaN,NaN,NaN,...,NaN,NaN,1.71,1.73,1.70,3.0,020219,Alls,Home,Chatty
4,31,Poptart,14,0,0,14,33%,102.0,7.29,2.0,...,3.65,NaN,NaN,NaN,2.22,3.0,020219,Alls,Home,Chatty

In [137]:
skaters = all_df[['#', 'Skater', 'Team', 'Game Date']]
u_skaters = skaters['#'].unique()

alls = skaters.loc[skaters['Team']=='Alls']
brawls = skaters.loc[skaters['Team']=='Brawls']

a_game_count = alls['Game Date'].count()
b_game_count = brawls['Game Date'].count()


total_games = skaters.groupby(['#']).count()

test = skaters.groupby(['#']).size()

alls.to_csv('alls.csv')
brawls.to_csv('brawls.csv')